### ISSUE TITLE
JTOP showing different opencv version

### ISSUE THREAD

**Issue by rsingh2083** [Qengineering/Face-Mask-Detection-Jetson-Nano#2]
I compiled opencv with cuda support but while python3 is showing opencv version as 3.3.1,
JTOP is showing opencv as 
`Opencv : 4.1.2   compiled  CUDA : YES`

Any explanation as to what could be happening ? I was able to run the mask detection with average FPS of 25 for single face on webcam. But just puzzled about mismatch between jtop and python's opencv verions.

**Comment by Qengineering** [comment]
JTOP uses the package version you just installed (4.1.2)
Python3 shows you the previous version (3.3.1) you probably forgot to uninstall before installing 4.1.2..
To avoid version conflicts, you must remove the old (3.3.1) version from your Nano.
Please find the python OpenCV library by using the next commands:
```
$ python3
>>> import cv2
>>> cv2.__file__
```
Remove this file with ```sudo rm```. Finish with ```sudo apt-get update```
Next go to your OpenCV build directory and re-run 
```
$ cd ~/opencv/build/ #(or something)
$ sudo make install  
$ sudo ldconfig
$ sudo apt-get update
```
If everything went well, you have now 4.1.2 also as Python version.
